### ISSUE TITLE
Gerar um diagrama com os resultados da análise do MOSS

### ISSUE THREAD

**Issue by andredrummond** [gnramos/cic-tools#2]
Considerando a saída gerada pelo MOSS, gerar um diagrama que indique visualmente o relacionamento entre os alunos cujos códigos possuam índice de similaridade igual ou superior a 30% (pode ser parametrizado). Cada aluno seria representado por uma forma geométrica contendo dentro dela as informações do cabeçalho do arquivo de código (nome, matrícula, turma e nota). Dois alunos estarão conectados se houver um relacionamento entre seus códigos (conforme regra anterior). Cada relacionamento seria um link para a página do MOSS contendo os detalhes.

**Comment by gnramos** [comment]
Agrupamento entre submissões similares definida com listas. O detalhamento de links e formas geométricas pode ser obtido com esta ferramenta: https://github.com/hjalti/mossum .
